#include <iostream>
using namespace std;

int main() {
    int num;
    cout << "Enter a number (0 - 100): ";
    cin >> num;

    if (num == 0) cout << "zero" << endl;
    if (num == 1) cout << "one" << endl;
    if (num == 2) cout << "two" << endl;
    if (num == 3) cout << "three" << endl;
    if (num == 4) cout << "four" << endl;
    if (num == 5) cout << "five" << endl;
    if (num == 6) cout << "six" << endl;
    if (num == 7) cout << "seven" << endl;
    if (num == 8) cout << "eight" << endl;
    if (num == 9) cout << "nine" << endl;
    if (num == 10) cout << "ten" << endl;
    if (num == 11) cout << "eleven" << endl;
    if (num == 12) cout << "twelve" << endl;
    if (num == 13) cout << "thirteen" << endl;
    if (num == 14) cout << "fourteen" << endl;
    if (num == 15) cout << "fifteen" << endl;
    if (num == 16) cout << "sixteen" << endl;
    if (num == 17) cout << "seventeen" << endl;
    if (num == 18) cout << "eighteen" << endl;
    if (num == 19) cout << "nineteen" << endl;
    if (num == 20) cout << "twenty" << endl;
    if (num == 21) cout << "twenty one" << endl;
    if (num == 22) cout << "twenty two" << endl;
    if (num == 23) cout << "twenty three" << endl;
    if (num == 24) cout << "twenty four" << endl;
    if (num == 25) cout << "twenty five" << endl;
    if (num == 26) cout << "twenty six" << endl;
    if (num == 27) cout << "twenty seven" << endl;
    if (num == 28) cout << "twenty eight" << endl;
    if (num == 29) cout << "twenty nine" << endl;
    if (num == 30) cout << "thirty" << endl;
    if (num == 31) cout << "thirty one" << endl;
    if (num == 32) cout << "thirty two" << endl;
    if (num == 33) cout << "thirty three" << endl;
    if (num == 34) cout << "thirty four" << endl;
    if (num == 35) cout << "thirty five" << endl;
    if (num == 36) cout << "thirty six" << endl;
    if (num == 37) cout << "thirty seven" << endl;
    if (num == 38) cout << "thirty eight" << endl;
    if (num == 39) cout << "thirty nine" << endl;
    if (num == 40) cout << "forty" << endl;
    if (num == 41) cout << "forty one" << endl;
    if (num == 42) cout << "forty two" << endl;
    if (num == 43) cout << "forty three" << endl;
    if (num == 44) cout << "forty four" << endl;
    if (num == 45) cout << "forty five" << endl;
    if (num == 46) cout << "forty six" << endl;
    if (num == 47) cout << "forty seven" << endl;
    if (num == 48) cout << "forty eight" << endl;
    if (num == 49) cout << "forty nine" << endl;
    if (num == 50) cout << "fifty" << endl;
    if (num == 51) cout << "fifty one" << endl;
    if (num == 52) cout << "fifty two" << endl;
    if (num == 53) cout << "fifty three" << endl;
    if (num == 54) cout << "fifty four" << endl;
    if (num == 55) cout << "fifty five" << endl;
    if (num == 56) cout << "fifty six" << endl;
    if (num == 57) cout << "fifty seven" << endl;
    if (num == 58) cout << "fifty eight" << endl;
    if (num == 59) cout << "fifty nine" << endl;
    if (num == 60) cout << "sixty" << endl;
    if (num == 61) cout << "sixty one" << endl;
    if (num == 62) cout << "sixty two" << endl;
    if (num == 63) cout << "sixty three" << endl;
    if (num == 64) cout << "sixty four" << endl;
    if (num == 65) cout << "sixty five" << endl;
    if (num == 66) cout << "sixty six" << endl;
    if (num == 67) cout << "sixty seven" << endl;
    if (num == 68) cout << "sixty eight" << endl;
    if (num == 69) cout << "sixty nine" << endl;
    if (num == 70) cout << "seventy" << endl;
    if (num == 71) cout << "seventy one" << endl;
    if (num == 72) cout << "seventy two" << endl;
    if (num == 73) cout << "seventy three" << endl;
    if (num == 74) cout << "seventy four" << endl;
    if (num == 75) cout << "seventy five" << endl;
    if (num == 76) cout << "seventy six" << endl;
    if (num == 77) cout << "seventy seven" << endl;
    if (num == 78) cout << "seventy eight" << endl;
    if (num == 79) cout << "seventy nine" << endl;
    if (num == 80) cout << "eighty" << endl;
    if (num == 81) cout << "eighty one" << endl;
    if (num == 82) cout << "eighty two" << endl;
    if (num == 83) cout << "eighty three" << endl;
    if (num == 84) cout << "eighty four" << endl;
    if (num == 85) cout << "eighty five" << endl;
    if (num == 86) cout << "eighty six" << endl;
    if (num == 87) cout << "eighty seven" << endl;
    if (num == 88) cout << "eighty eight" << endl;
    if (num == 89) cout << "eighty nine" << endl;
    if (num == 90) cout << "ninety" << endl;
    if (num == 91) cout << "ninety one" << endl;
    if (num == 92) cout << "ninety two" << endl;
    if (num == 93) cout << "ninety three" << endl;
    if (num == 94) cout << "ninety four" << endl;
    if (num == 95) cout << "ninety five" << endl;
    if (num == 96) cout << "ninety six" << endl;
    if (num == 97) cout << "ninety seven" << endl;
    if (num == 98) cout << "ninety eight" << endl;
    if (num == 99) cout << "ninety nine" << endl;
    if (num == 100) cout << "one hundred" << endl;
    return 0;
}